### ISSUE TITLE
JSON or quickJSON?

### ISSUE THREAD

**Issue by at0g** [iambumblehead/xhrgo#2]
The readme says `JSON`, the code says otherwise.

https://github.com/iambumblehead/xhrgo/blob/master/xhrgo.js#L132

```
import xhr from 'xhrgo';

console.log(typeof xhr.JSON) // undefined
console.log(typeof xhr.quickJSON) // function
```

**Comment by iambumblehead** [comment]
Do you prefer one name or the other?

**Comment by iambumblehead** [comment]
The readme is updated

**Comment by at0g** [comment]
Thanks for the quick response @iambumblehead 
Perhaps the readme on xhrgoform could do with a refresh too.
Cheers

**Comment by iambumblehead** [comment]
@at0g I updated the README for both packages just now. Thanks for letting me know.
