### ISSUE TITLE
WTF - Errors on 2xx status codes?

### ISSUE THREAD

**Issue by at0g** [iambumblehead/xhrgo#3]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success

https://github.com/iambumblehead/xhrgo/blob/master/xhrgo.js#L120-L123

**Comment by iambumblehead** [comment]
@at0g thank you! I will correct it this evening

**Comment by at0g** [comment]
Thanks  @iambumblehead  - I've added this as a workaround in the interim:

```
/2\d\d/.test(err.status)
```

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/xhrgo/commit/a131e55b7778a5b54a8bd867d0068cc5f6e8475a

@at0g I added and smoke tested your re, thanks
